<?php

/**
 * @file
 * Contains multi_somewall.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function multi_somewall_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the somewall module.
    case 'help.page.multi_somewall':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Somewall for twitter, facebook, rss and instagram') . '</p>';
      return $output;

    default:
  }
}

/**
 * Theme hook
 */
function multi_somewall_theme($existing, $type, $theme, $path) {
  return array(
    'multi_somewall' => array(
      'variables' => array('title' => 'Default title', 'content' => null),
      'template' => 'block--multi_somewall',
      '#attached' => array(
        'library' =>  array(
          'multi_somewall/socialfeed'
        ),
      ),
    ),
  );
}